default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV.fetch('DB_USERNAME') %>
  password: <%= ENV.fetch('DB_PASSWORD') %>

development:
  <<: *default
  database: <%= ENV.fetch('DB_DEVELOPMENT') %>

test:
  <<: *default
  database: <%= ENV.fetch('DB_TEST') %>

production:
  url: <%= ENV.fetch('DATABASE_URL') %>
